language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.8

before_install: 
  - pip install wheel

install:
   - pip install -r dependencies.txt
   - pip install .

branches:
  only:
      - master

notifications:
  email:
    recipients: 
      - victoria.ruiz.serra@gmail.com
    on_success: never
    on_failure: always